### ISSUE TITLE
Search-API of Rudolf: Undefined index: label

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/rudolf#15]
Querying the Search-API of Rudolf:
http://eis-openbudgets.iais.fraunhofer.de/search/package?size=10000&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiJkYTM0ZWY2Y2RiM2M2ZGMzZjIxNjg2ZWJjYWEyZjc0YiIsImV4cCI6MTQ2OTEwNjY0MX0.brNRaLpZW9zF8U0NoFFnyxxeHaqpGo3SidpLlCR180Q
via the OS-Viewer:  http://eis-openbudgets.iais.fraunhofer.de/viewer/  results in an error currently.

This is from the Laraval.logs in /srv2/obeu/integration/volumes/rudolf/log on the Server:
[2016-07-19 13:57:29] production.ERROR: ErrorException: Undefined index: label in /var/www/rudolf/app/Model/SearchResult.php:109
Stack trace:
#0 /var/www/rudolf/app/Model/SearchResult.php(109): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/rudolf...', 109, Array)
#1 /var/www/rudolf/app/Model/SearchResult.php(24): App\Model\SearchResult->load()

**Comment by schmaluk** [comment]
As discussed in the Meeting today, the OS-Viewer on our OBEU-Server should use now the Search API implemented at OS-side. As pointed out by @pwalsh our RDF-datasets not going through OS-system will be excluded from their Search API. But as @jindrichmynarz commented today UEP might provide a RDF-to-FDP-Pipeline later which will solve this Problem.
